---
title: "Midterm Project"
author: "Sofia Zandipour"
date: "October 12, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(tidyr)
impacts <- read_csv("impacts.csv")
```


##Tidying Data##
```{r}
impacts2 <- rename(impacts, name = "Object Name", start = "Period Start", end = "Period End", possible_impacts = "Possible Impacts", impact_prob = "Cumulative Impact Probability", velocity = "Asteroid Velocity", magnitude = "Asteroid Magnitude", diameter = "Asteroid Diameter (km)", palermo = "Cumulative Palermo Scale", max_palermo = "Maximum Palermo Scale", torino = "Maximum Torino Scale") %>%
print(impacts2)
```

```{r}
impacts3 <- select(impacts2, -impact_prob, -max_palermo, -torino) %>%
  mutate(year_range = end - start)
print(impacts3)
```

##Data Analysis##

####Which objects/asteroid are most likely to hit Earth?"
```{r}
impacts4 <- filter(impacts3, palermo >-4.0)
  
ggplot(data=impacts4)+
  geom_jitter(mapping=aes(x=magnitude, y=possible_impacts, color=name))
```

```{r}
ggplot(data=impacts3)+
  geom_histogram(mapping=aes(x=possible_impacts), bins=100) + 
  coord_cartesian(xlim = c(600, 1200), ylim = c(0, 2))
```
```{r}
ggplot(data=impacts3)+
  geom_jitter(mapping=aes(x=diameter, y=velocity))
```

